# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Applifare Technologies Private Limited
email: help@applifare.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
domain: applifare.github.io
url: "https://applifare.github.io" # the subpath of your site, e.g. /blog
baseurl: "/test-website" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll
formsubmit_slug: "4e2c75415841513b772861ab9d998d6a"

permalink: /blog/:title:output_ext

collections:
  - services

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

### Pagination config
pagination:
  enabled: true
  per_page: 5
  permalink: "page/:num/"
  title: ":title - page :num of :total"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  trail:
    before: 2
    after: 2
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

autopages:
  # Site-wide kill switch, disable here and it doesn't run at all
  enabled: true

  # Category pages, omit entire config element to disable
  categories:
    # Optional, the list of layouts that should be processed for every category found in the site
    layouts:
      - "blogs.html"
    # Optional, the title that each category paginate page should get (:cat is replaced by the Category name)
    title: "Blogs in category :cat"
    # Optional, the permalink for the  pagination page (:cat is replaced),
    # the pagination permalink path is then appended to this permalink structure
    permalink: "/category/:cat"
    # Optional, when true logging related to category pages will be supressed.
    silent: false
    slugify:
      mode: "default" # :cat is slugified. Modes: default, raw, pretty, ascii, latin
      case: false

  tags:
    layouts:
      - "blogs.html"
    title: "Blogs tagged with :tag" # :tag is replaced by the tag name
    permalink: "/tag/:tag"
    silent: false
    slugify:
      mode: "default" # :tag is slugified.
      case: false
